<?php
require 'vendor/autoload.php';

use Dompdf\Dompdf;

// Initialize Dompdf
$dompdf = new Dompdf();

// HTML content
$html = '<h1>Hello, World!</h1><p>This is a PDF generated by Dompdf.</p>';

// Load content into Dompdf
$dompdf->loadHtml($html);

// Set paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the PDF
$dompdf->render();

// Output the PDF to the browser
$dompdf->stream("sample.pdf", ["Attachment" => false]);
?>